name: Build, test and deploy ASP.Net Core app to Azure Web App - backendtextadventure-game

on:
  push:
    paths:
    - 'backend-textadventure/textadventure_backend/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build
        working-directory: backend-textadventure/textadventure_backend
        run: dotnet build --configuration Release

      - name: Test
        working-directory: ./backend-textadventure/textadventure_backend
        run: dotnet test --verbosity normal

      - name: Publish
        working-directory: backend-textadventure/textadventure_backend
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webadventure-game'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_88A7342132244AD498B6B3BE0251C454 }}
          package: .
