name: Build, Test and Deploy ASP.Net Core app to Azure Web App - backendtextadventure

on: [push]

jobs:
 cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Cypress run
        working-directory: frontend-textadventure
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start